spring:
  application:
    name: feature-flag-service

  datasource:
    url: jdbc:h2:file:./data/featureflags
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
